import React, { useState, useEffect, useMemo } from 'react';
import { Helmet } from 'react-helmet';
import { format, parseISO } from 'date-fns';
import { Wallet, Search, Filter, RefreshCw, AlertCircle, ArrowUpRight, ArrowDownRight, PlusCircle, Settings, Users, TrendingDown, Trash2, Mail } from 'lucide-react';
import { toast } from 'sonner';

import { useCashbookData } from '@/hooks/useCashbookData.js';
import { useCashbookInit } from '@/hooks/useCashbookInit.js';
import pb from '@/lib/pocketbaseClient.js';
import { useAuth } from '@/contexts/AuthContext.jsx';

import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { motion } from 'framer-motion';

import ExpenseModal from '@/components/ExpenseModal.jsx';
import AddIncomeModal from '@/components/AddIncomeModal.jsx';
import EditOpeningBalanceModal from '@/components/EditOpeningBalanceModal.jsx';
import CashbookTransactionList from '@/components/CashbookTransactionList.jsx';
import SendMailDialog from '@/components/SendMailDialog.jsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function CashbookPage() {
  const { currentUser } = useAuth();
  const { isInitialized } = useCashbookInit();
  const { transactions, isLoading: isTxLoading, error, refetch } = useCashbookData();

  const [isExpenseModalOpen, setIsExpenseModalOpen] = useState(false);
  const [isIncomeModalOpen, setIsIncomeModalOpen] = useState(false);
  const [isOpeningBalanceModalOpen, setIsOpeningBalanceModalOpen] = useState(false);
  const [openingBalanceRecord, setOpeningBalanceRecord] = useState(null);
  const [isResetting, setIsResetting] = useState(false);
  const [mailOpen, setMailOpen] = useState(false);
  const [mailData, setMailData] = useState({ recipient: '', subject: '', body: '', html: '', label: '', attachment: null });

  const generateCashbookPDFBlob = () => {
    try {
      const doc = new jsPDF();
      const userName = currentUser?.name || pb.authStore.model?.name || 'Admin';
      
      // Header
      doc.setFontSize(20);
      doc.setTextColor(15, 23, 42);
      doc.text('Cashbook Statement', 14, 22);
      
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by: ${userName}`, 14, 30);
      doc.text(`Date: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 14, 35);
      
      const openingAmt = openingBalanceRecord ? (openingBalanceRecord.transaction_type === 'Expense' ? -Number(openingBalanceRecord.amount) : Number(openingBalanceRecord.amount)) : 0;
      const totalIncome = processedTransactions.filter(t => !t.isOpeningBalance && t.isIncome).reduce((a, b) => a + (Number(b.amount) || 0), 0);
      const totalOutflow = processedTransactions.filter(t => !t.isOpeningBalance && !t.isIncome).reduce((a, b) => a + (Number(b.amount) || 0), 0);
      const netBalance = displayBalance;

      // Summary Box
      doc.setFillColor(248, 250, 252);
      doc.rect(14, 40, 182, 25, 'F');
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(10);
      doc.text(`Opening Balance: Rs. ${openingAmt.toFixed(2)}`, 20, 48);
      doc.text(`Total Income: Rs. ${totalIncome.toFixed(2)}`, 20, 58);
      doc.text(`Total Outflow: Rs. ${totalOutflow.toFixed(2)}`, 110, 48);
      doc.setFont(undefined, 'bold');
      doc.text(`Closing Balance: Rs. ${netBalance.toFixed(2)}`, 110, 58);
      doc.setFont(undefined, 'normal');

      // Table
      const tableColumn = ["Date", "Category", "Description", "Type", "Amount", "Balance"];
      const tableRows = processedTransactions.map(tx => [
        format(new Date(tx.date), 'dd/MM/yyyy'),
        tx.category || 'Manual',
        tx.description || '-',
        tx.isIncome ? 'Cr' : 'Dr',
        `Rs. ${Number(tx.amount).toFixed(2)}`,
        `Rs. ${Number(tx.running_balance).toFixed(2)}`
      ]);

      doc.autoTable({
        head: [tableColumn],
        body: tableRows,
        startY: 75,
        theme: 'striped',
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: [15, 23, 42], textColor: 255 },
        alternateRowStyles: { fillColor: [248, 250, 252] }
      });

      return doc.output('blob');
    } catch (e) {
      console.error('Failed to generate PDF:', e);
      return null;
    }
  };

  const triggerEmailCashbook = () => {
    const fmt = (n) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Math.abs(n || 0));
    const txs = transactions || [];
    const income = txs.filter(t => t.transaction_type === 'Income' || t.transaction_type === 'credit').reduce((a, b) => a + Number(b.amount || 0), 0);
    const expense = txs.filter(t => t.transaction_type !== 'Income' && t.transaction_type !== 'credit').reduce((a, b) => a + Number(b.amount || 0), 0);
    const html = `<div style="font-family:sans-serif;max-width:520px;margin:0 auto;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="background:linear-gradient(135deg,#1e293b,#0f172a);padding:20px 24px"><p style="color:#94a3b8;font-size:11px;font-weight:700;letter-spacing:2px;margin:0 0 6px">JAI BHAVANI CARGO</p><h2 style="color:#f8fafc;font-size:20px;font-weight:800;margin:0">Cashbook Summary</h2></div><div style="padding:20px 24px;background:#f8fafc"><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px"><p style="color:#64748b;font-size:10px;font-weight:700;letter-spacing:1px;margin:0 0 4px">INCOME</p><p style="color:#059669;font-size:18px;font-weight:800;margin:0">${fmt(income)}</p></div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px"><p style="color:#64748b;font-size:10px;font-weight:700;letter-spacing:1px;margin:0 0 4px">EXPENSE</p><p style="color:#e11d48;font-size:18px;font-weight:800;margin:0">${fmt(expense)}</p></div><div style="background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px"><p style="color:#64748b;font-size:10px;font-weight:700;letter-spacing:1px;margin:0 0 4px">BALANCE</p><p style="color:#6366f1;font-size:18px;font-weight:800;margin:0">${fmt(income - expense)}</p></div></div><p style="margin-top:14px;font-size:11px;color:#94a3b8;text-align:center">Generated from Jai Bhavani Cargo Cashbook</p></div></div>`;
    
    const pdfBlob = generateCashbookPDFBlob();
    const fileName = `cashbook_summary_${format(new Date(), 'yyyyMMdd')}.pdf`;

    setMailData({ 
      recipient: '', 
      subject: 'Cashbook Summary – Jai Bhavani Cargo', 
      body: 'Hi, please find the attached Cashbook statement document.', 
      html, 
      label: 'Cashbook Summary',
      attachment: pdfBlob ? { blob: pdfBlob, name: fileName } : null
    });
    setMailOpen(true);
  };
  
  const [employees, setEmployees] = useState([]);
  
  const [filters, setFilters] = useState({
    search: '',
    category: 'all',
    type: 'all',
    employee: 'all',
    dateFrom: '',
    dateTo: ''
  });

  const fetchOpeningBalance = async () => {
    try {
      const record = await pb.collection('cashbook').getFirstListItem('description="Opening Balance" || reference_type="opening_balance"', { 
        sort: '-created', 
        $autoCancel: false 
      });
      setOpeningBalanceRecord(record);
    } catch (e) {
      setOpeningBalanceRecord(null);
    }
  };

  const fetchEmployees = async () => {
    try {
      const records = await pb.collection('employees').getFullList({ sort: 'name', $autoCancel: false });
      setEmployees(records);
    } catch (err) {
      console.error('Failed to fetch employees for cashbook filters', err);
    }
  };

  useEffect(() => {
    fetchOpeningBalance();
    fetchEmployees();
  }, [transactions]);

  // Automated one-time migration to wipe extra cashbook entries and set balance to -153,500 if requested
  const handleWipeAndResetCashbook = async () => {
    if (!window.confirm("Are you sure you want to delete all cashbook entries and set the current balance to -₹153,500? (Your expense logs will NOT be affected)")) {
      return;
    }

    setIsResetting(true);
    const toastId = toast.loading("Deleting cashbook entries and resetting balance to -₹153,500...");

    try {
      // 1. Fetch all cashbook records
      const allRecords = await pb.collection('cashbook').getFullList({ $autoCancel: false });
      
      // 2. Delete all records
      for (const rec of allRecords) {
        await pb.collection('cashbook').delete(rec.id, { $autoCancel: false });
      }

      // 3. Create fresh Opening Balance entry of 153500 (Expense => -153,500)
      const openingPayload = {
        amount: 153500,
        date: new Date().toISOString(),
        description: 'Opening Balance',
        category: 'Manual',
        transaction_type: 'Expense',
        status: 'Completed',
        reference_type: 'opening_balance',
        added_by: currentUser?.id || ''
      };

      await pb.collection('cashbook').create(openingPayload, { $autoCancel: false });
      toast.success("Cashbook entries wiped successfully! Current balance is set to -₹153,500.", { id: toastId });
      
      await refetch();
      await fetchOpeningBalance();
    } catch (err) {
      console.error("Cashbook reset error:", err);
      toast.error(err.message || "Failed to reset cashbook", { id: toastId });
    } finally {
      setIsResetting(false);
    }
  };

  const employeesMap = useMemo(() => {
    return employees.reduce((acc, emp) => {
      acc[emp.id] = emp.name;
      return acc;
    }, {});
  }, [employees]);

  const isLoading = !isInitialized || isTxLoading;

  const processedTransactions = useMemo(() => {
    if (!transactions) return [];
    
    // Filter out the opening balance record from regular transactions list
    const regularTxs = transactions.filter(t => t.description !== 'Opening Balance' && t.reference_type !== 'opening_balance');
    
    let openingAmt = 0;
    if (openingBalanceRecord) {
      const isCredit = openingBalanceRecord.transaction_type === 'Income' || openingBalanceRecord.transaction_type === 'credit';
      openingAmt = isCredit ? Number(openingBalanceRecord.amount) : -Number(openingBalanceRecord.amount);
    }
    
    let currentBal = openingAmt;
    const asc = [...regularTxs].reverse();
    
    const calculated = asc.map(tx => {
      const amt = Number(tx.amount) || 0;
      const isCredit = tx.transaction_type === 'Income' || tx.transaction_type === 'credit';
      if (isCredit) {
        currentBal += amt;
      } else {
        currentBal -= amt;
      }
      return {
        ...tx,
        running_balance: currentBal,
        isIncome: isCredit
      };
    });
    
    const reversed = calculated.reverse();
    
    // Prepend Opening Balance item if it exists
    if (openingBalanceRecord) {
      reversed.push({
        id: openingBalanceRecord.id || 'ob-item',
        date: openingBalanceRecord.date || new Date().toISOString(),
        isOpeningBalance: true,
        running_balance: openingAmt,
        description: 'Opening Balance',
        category: 'Opening Balance',
        amount: Math.abs(openingAmt)
      });
    }
    
    return reversed;
  }, [transactions, openingBalanceRecord]);

  const filteredTransactions = useMemo(() => {
    return processedTransactions.filter(tx => {
      if (tx.isOpeningBalance) return true;

      if (filters.category !== 'all' && tx.category !== filters.category) return false;
      if (filters.type !== 'all') {
        const isIncome = tx.transaction_type === 'Income' || tx.transaction_type === 'credit';
        if (filters.type === 'Income' && !isIncome) return false;
        if (filters.type === 'Expense' && isIncome) return false;
      }
      if (filters.employee !== 'all' && tx.employee_id !== filters.employee) return false;
      
      if (filters.dateFrom) {
        if (new Date(tx.date).getTime() < new Date(filters.dateFrom).getTime()) return false;
      }
      if (filters.dateTo) {
        if (new Date(tx.date).getTime() >= new Date(filters.dateTo).getTime() + 86400000) return false;
      }
      
      if (filters.search) {
        const q = filters.search.toLowerCase();
        if (!tx.description?.toLowerCase().includes(q) && !tx.category?.toLowerCase().includes(q)) {
          return false;
        }
      }
      
      return true;
    });
  }, [processedTransactions, filters]);

  const formatCurrency = (val) => {
    const absVal = Math.abs(val || 0);
    const formatted = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(absVal);
    return val < 0 ? `-${formatted}` : formatted;
  };

  const displayBalance = useMemo(() => {
    let openingAmt = 0;
    if (openingBalanceRecord) {
      const isCredit = openingBalanceRecord.transaction_type === 'Income' || openingBalanceRecord.transaction_type === 'credit';
      openingAmt = isCredit ? Number(openingBalanceRecord.amount) : -Number(openingBalanceRecord.amount);
    }
    
    const regularTxs = transactions ? transactions.filter(t => t.description !== 'Opening Balance' && t.reference_type !== 'opening_balance') : [];
    const totalIncome = regularTxs.filter(t => t.transaction_type === 'Income' || t.transaction_type === 'credit').reduce((a, b) => a + (Number(b.amount) || 0), 0);
    const totalOutflow = regularTxs.filter(t => t.transaction_type !== 'Income' && t.transaction_type !== 'credit').reduce((a, b) => a + (Number(b.amount) || 0), 0);
    
    return openingAmt + totalIncome - totalOutflow;
  }, [transactions, openingBalanceRecord]);

  const isNegativeBalance = displayBalance < 0;

  if (error) {
    const errorMessage = typeof error === 'string' ? error : error?.message || 'An error occurred';
    
    return (
      <div className="h-full w-full bg-background flex flex-col items-center justify-center p-8 animate-in fade-in duration-300">
        <div className="p-4 bg-destructive/10 rounded-full mb-4">
          <AlertCircle className="w-10 h-10 text-destructive" />
        </div>
        <h2 className="text-2xl font-bold mb-2">Failed to load cashbook</h2>
        <p className="text-muted-foreground mb-6 text-center max-w-md">{errorMessage}</p>
        <Button onClick={refetch} className="gap-2 rounded-xl shadow-sm">
          <RefreshCw className="w-4 h-4" /> Retry Connection
        </Button>
      </div>
    );
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };
  const itemVariants = {
    hidden: { opacity: 0, y: 15 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <div className="h-full w-full bg-background flex flex-col">
      <Helmet>
        <title>Cashbook Ledger | Transport Manager</title>
      </Helmet>
      
      <main className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-10">
        <motion.div initial="hidden" animate="visible" variants={containerVariants} className="space-y-8">
          
          <motion.div variants={itemVariants} className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-5">
            <div>
              <h1 className="text-3xl sm:text-4xl font-heading font-extrabold tracking-tight text-foreground flex items-center gap-3">
                <div className="p-2 bg-primary/10 rounded-xl">
                  <Wallet className="w-7 h-7 text-primary" />
                </div>
                Live Cashbook
              </h1>
              <p className="text-muted-foreground mt-2 max-w-2xl">
                Real-time tracking of all integrated expenses, advances, and manual income entries.
              </p>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <Button 
                onClick={handleWipeAndResetCashbook} 
                disabled={isResetting}
                variant="outline" 
                className="rounded-xl shadow-sm gap-2 border-destructive/30 text-destructive hover:bg-destructive/10"
              >
                <Trash2 className="w-4 h-4" /> Reset Balance to -₹1.53L
              </Button>
              <Button onClick={() => setIsOpeningBalanceModalOpen(true)} variant="secondary" className="rounded-xl shadow-sm gap-2 bg-secondary text-secondary-foreground">
                <Settings className="w-4 h-4" /> Set Opening Balance
              </Button>
              <Button onClick={() => setIsIncomeModalOpen(true)} className="rounded-xl shadow-sm gap-2 bg-success hover:bg-success/90 text-success-foreground">
                <PlusCircle className="w-4 h-4" /> Add Income
              </Button>
              <Button onClick={triggerEmailCashbook} variant="outline" className="rounded-xl shadow-sm gap-2 text-blue-400 border-blue-500/30 hover:bg-blue-500/10">
                <Mail className="w-4 h-4" /> Email Summary
              </Button>
              <Button onClick={() => setIsExpenseModalOpen(true)} className="rounded-xl shadow-sm gap-2">
                <PlusCircle className="w-4 h-4" /> Add Expense
              </Button>
            </div>
          </motion.div>

          {isLoading ? (
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <Skeleton className="h-36 rounded-2xl" />
                <Skeleton className="h-36 rounded-2xl" />
                <Skeleton className="h-36 rounded-2xl" />
              </div>
              <Skeleton className="h-[400px] rounded-2xl" />
            </div>
          ) : (
            <>
              <motion.div variants={itemVariants} className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <Card className={`border-border shadow-sm bg-card overflow-hidden relative ${isNegativeBalance ? 'ring-2 ring-destructive/20' : ''}`}>
                  <div className="absolute right-0 top-0 p-4 opacity-5 pointer-events-none">
                    {isNegativeBalance ? <TrendingDown className="w-24 h-24" /> : <Wallet className="w-24 h-24" />}
                  </div>
                  <CardContent className="p-6 relative z-10 flex flex-col justify-between h-full">
                    <div>
                      <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Current Balance</p>
                      <h3 className={`text-4xl font-extrabold mt-4 tabular-nums tracking-tight ${isNegativeBalance ? 'text-destructive' : 'text-foreground'}`}>
                        {formatCurrency(displayBalance)}
                      </h3>
                      {isNegativeBalance && (
                        <p className="text-xs text-destructive/80 mt-2 font-medium">Account in debt</p>
                      )}
                    </div>
                    {openingBalanceRecord && (
                      <div className="mt-4 pt-4 border-t border-border/50">
                        <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Opening Balance</p>
                        <p className="text-sm font-semibold tabular-nums text-foreground">
                          {formatCurrency(openingBalanceRecord.transaction_type === 'Expense' || openingBalanceRecord.transaction_type === 'credit' ? -openingBalanceRecord.amount : openingBalanceRecord.amount)}
                        </p>
                      </div>
                    )}
                  </CardContent>
                </Card>

                <Card className="border-border shadow-sm bg-card overflow-hidden">
                  <CardContent className="p-6 flex flex-col justify-between h-full">
                    <div>
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Total Income</p>
                        <div className="p-2 bg-success/10 rounded-lg">
                          <ArrowUpRight className="w-4 h-4 text-success" />
                        </div>
                      </div>
                      <h3 className="text-3xl font-bold mt-4 text-success tabular-nums">
                        {formatCurrency(processedTransactions.filter(t => !t.isOpeningBalance && t.isIncome).reduce((a, b) => a + (Number(b.amount) || 0), 0))}
                      </h3>
                    </div>
                    <p className="text-xs text-muted-foreground mt-4">
                      {processedTransactions.filter(t => !t.isOpeningBalance && t.isIncome).length} credit transaction(s)
                    </p>
                  </CardContent>
                </Card>

                <Card className="border-border shadow-sm bg-card overflow-hidden">
                  <CardContent className="p-6 flex flex-col justify-between h-full">
                    <div>
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Total Outflow</p>
                        <div className="p-2 bg-destructive/10 rounded-lg">
                          <ArrowDownRight className="w-4 h-4 text-destructive" />
                        </div>
                      </div>
                      <h3 className="text-3xl font-bold mt-4 text-destructive tabular-nums">
                        {formatCurrency(processedTransactions.filter(t => !t.isOpeningBalance && !t.isIncome).reduce((a, b) => a + (Number(b.amount) || 0), 0))}
                      </h3>
                    </div>
                    <p className="text-xs text-muted-foreground mt-4">
                      {processedTransactions.filter(t => !t.isOpeningBalance && !t.isIncome).length} debit transaction(s)
                    </p>
                  </CardContent>
                </Card>
              </motion.div>

              <motion.div variants={itemVariants} className="space-y-4">
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-muted/20 p-4 rounded-2xl border border-border">
                  <div className="relative w-full sm:w-80">
                    <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
                    <Input 
                      placeholder="Search transactions..." 
                      value={filters.search}
                      onChange={e => setFilters({...filters, search: e.target.value})}
                      className="pl-9 bg-background rounded-xl"
                    />
                  </div>
                  
                  <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
                    <Select value={filters.type} onValueChange={v => setFilters({...filters, type: v})}>
                      <SelectTrigger className="w-[120px] bg-background rounded-xl">
                        <SelectValue placeholder="Type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Types</SelectItem>
                        <SelectItem value="Income">Income</SelectItem>
                        <SelectItem value="Expense">Expense</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <CashbookTransactionList 
                  transactions={filteredTransactions} 
                  employeesMap={employeesMap} 
                  refetch={refetch} 
                />
              </motion.div>
            </>
          )}
        </motion.div>
      </main>

      <ExpenseModal 
        isOpen={isExpenseModalOpen}
        onClose={() => setIsExpenseModalOpen(false)}
        onSuccess={refetch}
      />
      <AddIncomeModal 
        isOpen={isIncomeModalOpen}
        onClose={() => setIsIncomeModalOpen(false)}
        onSuccess={refetch}
      />
      <EditOpeningBalanceModal 
        isOpen={isOpeningBalanceModalOpen}
        onClose={() => setIsOpeningBalanceModalOpen(false)}
        existingRecord={openingBalanceRecord}
        onSuccess={() => {
          fetchOpeningBalance();
          refetch();
        }}
      />
      <SendMailDialog
        isOpen={mailOpen}
        onOpenChange={setMailOpen}
        defaultRecipient={mailData.recipient}
        defaultSubject={mailData.subject}
        defaultBody={mailData.body}
        richHtmlContent={mailData.html}
        contextLabel={mailData.label}
        defaultAttachment={mailData.attachment}
      />
    </div>
  );
}